branch-defaults:
  master:
    environment: EleveWebsite-dev
    group_suffix: null
global:
  application_name: EleveWebsite
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: sa-east-1
  profile: eb-cli
  repository: null
  sc: git
