# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50)),
                ('nome_ingrediente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_de_preparo', models.TextField()),
                ('nivel_de_dificuldade', models.IntegerField()),
                ('ingredientes', models.ManyToManyField(to='main_site.Ingrediente')),
            ],
        ),
    ]
