# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
