# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_receita_nome_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte_da_Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Passo_da_Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='modo_de_preparo',
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=100),
        ),
        migrations.AddField(
            model_name='receita',
            name='foto_da_receita',
            field=models.ImageField(null=True, upload_to=main_site.models.Receita.get_image_path),
        ),
        migrations.AddField(
            model_name='receita',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_de_preparo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome_ingrediente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nivel_de_dificuldade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(default='Receita', max_length=100),
        ),
        migrations.AddField(
            model_name='parte_da_receita',
            name='ingredientes',
            field=models.ManyToManyField(to='main_site.Ingrediente'),
        ),
        migrations.AddField(
            model_name='parte_da_receita',
            name='modo_de_preparo',
            field=models.ManyToManyField(to='main_site.Passo_da_Receita'),
        ),
        migrations.AddField(
            model_name='receita',
            name='subpartes',
            field=models.ManyToManyField(to='main_site.Parte_da_Receita'),
        ),
    ]
