# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20161211_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='image_url',
            new_name='url_da_imagem',
        ),
    ]
