# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20161211_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte_da_receita',
            name='nome_da_parte',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
