# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20161211_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='C:/media/')),
            ],
        ),
    ]
