# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_receita',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/<function Foto_Receita.upload_filename at 0x00000249CA7218C8>'),
        ),
    ]
