# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20161219_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_receita',
            name='foto',
            field=models.ImageField(null=True, upload_to=main_site.models.Foto_Receita.upload_filename),
        ),
    ]
