# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0012_auto_20161219_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', models.ImageField(null=True, upload_to=main_site.models.Perfil.get_image_path)),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('data_nascimento', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='foto_receita',
            name='foto',
            field=models.ImageField(null=True, upload_to=main_site.models.Foto_Receita.upload_filename),
        ),
        migrations.AddField(
            model_name='paciente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Perfil'),
        ),
        migrations.AddField(
            model_name='coach',
            name='pacientes_supervisionados',
            field=models.ManyToManyField(to='main_site.Paciente'),
        ),
        migrations.AddField(
            model_name='coach',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Perfil'),
        ),
    ]
