# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_auto_20170111_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Passo_na_Parte_Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_passo_na_parte', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='parte_da_receita',
            name='modo_de_preparo',
            field=models.ManyToManyField(related_name='preparo', to='main_site.Passo_da_Receita'),
        ),
        migrations.AddField(
            model_name='ordem_passo_na_parte_receita',
            name='parte_da_receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Parte_da_Receita'),
        ),
        migrations.AddField(
            model_name='ordem_passo_na_parte_receita',
            name='passo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Passo_da_Receita'),
        ),
        migrations.AddField(
            model_name='parte_da_receita',
            name='modo_de_preparo_subparte',
            field=models.ManyToManyField(through='main_site.Ordem_Passo_na_Parte_Receita', to='main_site.Passo_da_Receita'),
        ),
    ]
