# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20170117_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte_da_receita',
            name='modo_de_preparo',
        ),
    ]
