# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_remove_parte_da_receita_modo_de_preparo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parte_da_receita',
            old_name='modo_de_preparo_subparte',
            new_name='modo_de_preparo',
        ),
    ]
