# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20170122_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatNameID', models.CharField(max_length=50)),
                ('coachParticipante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Coach')),
                ('pacientesParticipantes', models.ManyToManyField(to='main_site.Paciente')),
            ],
        ),
    ]
