# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='coachUsername',
            field=models.CharField(default='Coach', max_length=50),
        ),
    ]
