# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_chat_coachusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Chat')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Coach')),
                ('pacientes', models.ManyToManyField(to='main_site.Paciente')),
            ],
        ),
    ]
