# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nome_grupo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
