# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_grupo_nome_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to=main_site.models.Foto_Perfil.upload_filename)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_perfil',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medida_abdominal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medida_cintura',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Foto_Perfil'),
        ),
    ]
