# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_auto_20170307_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
