# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0023_grupo_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLog_Peso',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('data', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_site.Paciente')),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical log_ peso',
            },
        ),
        migrations.CreateModel(
            name='Log_Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Paciente')),
            ],
        ),
    ]
