# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0024_historicallog_peso_log_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario_Alimentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=50)),
                ('satisfacao', models.CharField(max_length=50)),
                ('diario_alimentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_refeicoes', to='main_site.Diario_Alimentar')),
            ],
        ),
        migrations.CreateModel(
            name='Porcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50, null=True)),
                ('ingrediente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_refeicao', models.CharField(max_length=50)),
                ('porcoes', models.ManyToManyField(to='main_site.Porcao')),
            ],
        ),
        migrations.AlterField(
            model_name='historicallog_peso',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='log_peso',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='log_refeicao',
            name='refeicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Refeicao'),
        ),
    ]
