# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0027_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLog_PesoBot',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_site.Participante')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical log_ peso bot',
            },
        ),
        migrations.CreateModel(
            name='Log_PesoBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data', models.DateTimeField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='Log_RefeicaoBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao_nome', models.CharField(max_length=100, null=True)),
                ('descricao_refeicao', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Participante')),
            ],
        ),
    ]
